
# Clear players inventory when they join the server
clear-inventory-on-join: true

# The item that will open the destination selector menu
destination-selector:
  slot: 4
  material: COMPASS
  name: "§6Destination Selector"
  skull-texture: ""
  amount: 1
  is-glowing: true
  lore: []

servers:
  redirect_server_name-a:
    max-players: 60
    max-protocol-version: 47 # Can be commented out if you want to allow all versions
    min-protocol-version: 47 # Can be commented out if you want to allow all versions
  redirect_server_name-b:
    max-players: 60
    max-protocol-version: 47 # Can be commented out if you want to allow all versions
    min-protocol-version: 47 # Can be commented out if you want to allow all versions


protocol-version:
  max:
    message:
      enabled: true
      content: "§cYou are using an unsupported version of Minecraft. Please use 1.20 ."
    title:
      enabled: true
      title: "§cUnsupported version"
      sub-title: "§cPlease use 1.20 ."
      fade-in: 20
      stay: 60
      fade-out: 20
  min:
    message:
      enabled: true
      content: "§cYou are using an unsupported version of Minecraft. Please use 1.20 ."
    title:
      enabled: true
      title: "§cUnsupported version"
      sub-title: "§cPlease use 1.20 ."
      fade-in: 20
      stay: 60
      fade-out: 20

# The amount of time in seconds between each check for the amount of players on a server
# Time in ticks
# 20 ticks = 1 second
check-server-count-interval: 100
