
# Clear players inventory when they join the server
clear-inventory-on-join: true

# The item that will open the destination selector menu
destination-selector:
  slot: 4
  material: COMPASS
  name: "§6Destination Selector"
  skull-texture: ""
  amount: 1
  is-glowing: true
  lore: []

servers:
  redirect-server-name-a:
    max-players: 60
    protocol-version:
        max-protocol: 47 # -1 to disable
        min-protocol: 47 # -1 to disable
        message:
          enabled: true
          content: "§cYou are using an unsupported version of Minecraft. Please use 1.20 ."
        title:
          enabled: true
          title: "§cUnsupported version"
          sub-title: "§cPlease use 1.20 ."
          fade-in: 20
          stay: 60
          fade-out: 20
  redirect-server-name-b:
    max-players: 60
    protocol-version:
        max-protocol: 47 # -1 to disable
        min-protocol: 47 # -1 to disable
        message:
          enabled: true
          content: "§cYou are using an unsupported version of Minecraft. Please use 1.20 ."
        title:
          enabled: true
          title: "§cUnsupported version"
          sub-title: "§cPlease use 1.20 ."
          fade-in: 20
          stay: 60
          fade-out: 20


# The amount of time in ticks between each check for the amount of players on a server
# Time in ticks
# 20 ticks = 1 second
check-server-count-interval: 100

waiting-list-indicator:
  # The title of the boss bar
  title: "Position {POSITION}"

  # The color of the boss bar
  # Possible values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarColor.html#enum-constant-summary
  color: "GREEN"

  # The style of the boss bar
  # Possible values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarStyle.html#enum-constant-summary
  style: "SOLID"
