
# Clear players inventory when they join the server
clear-inventory-on-join: true

# The default selected item slot when the player joins the server
default-selected-item:
  enabled: true
  slot: 4 # Must be between 0 and 8

# The item that will open the destination selector menu
destination-selector:
  slot: 4
  material: COMPASS
  name: "§6Destination Selector"
  skull-texture: ""
  amount: 1
  is-glowing: true
  lore: []

servers:
  redirect-server-name-a: # Must be the same name as the selector_menu file in menu folder in *.meta.server
    max-players: 60
    protocol-version:
        max-protocol: 47 # -1 to disable
        min-protocol: 47 # -1 to disable
        message:
          enabled: true
          content: "§cYou are using an unsupported version of Minecraft. Please use 1.20 ."
        title:
          enabled: true
          title: "§cUnsupported version"
          sub-title: "§cPlease use 1.20 ."
          fade-in: 20
          stay: 60
          fade-out: 20
  redirect-server-name-b: # Must be the same name as the selector_menu file in menu folder in *.meta.server
    max-players: 60
    protocol-version:
        max-protocol: 47 # -1 to disable
        min-protocol: 47 # -1 to disable
        message:
          enabled: true
          content: "§cYou are using an unsupported version of Minecraft. Please use 1.20 ."
        title:
          enabled: true
          title: "§cUnsupported version"
          sub-title: "§cPlease use 1.20 ."
          fade-in: 20
          stay: 60
          fade-out: 20
#  redirect-server-name-c: # Must be the same name as the selector_menu file in menu folder in *.meta.server
#    max-players: 60
#    protocol-version:
#      max-protocol: 47 # -1 to disable
#      min-protocol: 47 # -1 to disable
#      message:
#        enabled: true
#        content: "§cYou are using an unsupported version of Minecraft. Please use 1.20 ."
#      title:
#        enabled: true
#        title: "§cUnsupported version"
#        sub-title: "§cPlease use 1.20 ."
#        fade-in: 20
#        stay: 60
#        fade-out: 20


# The amount of time in ticks between each check for the number of players on a server.
# This is used to send players when a slot is available with more ore less time.
# Time in ticks
# 20 ticks = 1 second
check-server-count-interval: 100

waiting-list-indicator:
  # The title of the boss bar
  # Use {POSITION} to display the player's position in the waiting list
  title: "Position {POSITION}"

  # The color of the boss bar
  # Possible values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarColor.html#enum-constant-summary
  color: "GREEN"

  # The style of the boss bar
  # Possible values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarStyle.html#enum-constant-summary
  style: "SOLID"
