name: Leap
author: Army_
version: '${project.version}'
main: fr.army.leap.LeapPlugin
api-version: '1.20'
description: 'A plugin that allows players to be teleported to other servers.'
depend:
  - ViaVersion
commands:
  leap:
    description: "Main command of the plugin"
    maintenance:
      description: "Set the maintenance mode of the given server"
      usage: "/leap maintenance <server>"
      permission: "leap.maintenance.<server>"
