name: WhereAreYouGoing
author: Army_
version: '${project.version}'
main: fr.army.leap.WhereAreYouGoingPlugin
api-version: '1.20'
description: 'A plugin that allows players to teleport to other servers.'
depend:
  - ViaVersion
commands:
  whereareyougoing:
    aliases:
      - wh
    description: "Main command of the plugin"
    maintenance:
      description: "Set the maintenance mode of the given server"
      usage: "/whereareyougoing maintenance <server>"
      permission: "wayg.maintenance.<server>"
