name: WhereAreYouGoing
author: Army_
version: '${project.version}'
main: fr.army.whereareyougoing.WhereAreYouGoingPlugin
api-version: '1.20'
description: 'A plugin that allows players to teleport to other servers.'
depend:
  - ViaVersion
